version: '3.8'
services:

  auth_service:
    container_name: auth_service
    image: auth-service
    depends_on:
      - postgres
      - jaeger
    environment:
      RUN_MODE: prod-like
    env_file:
      - .env
    networks:
      - auth_api_net

  nginx:
    image: nginx:latest
    profiles:
      - prod-like
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    networks:
      - auth_api_net
      - online_cinema
    ports:
      - "8080:80"

  postgres:
    image: postgres:15
    container_name: db_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_api_net

  redis:
    image: redis:6.2.14
    networks:
      - auth_api_net
 
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - auth_api_net
    ports:
      - 16686:16686
      - 6831:6831/udp

networks:
  auth_api_net:
    driver: bridge
  online_cinema:
    external: true

volumes:
  postgres_data:
